#!/bin/bash

### BEGIN INIT INFO
# Provides: SpeedTest
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: SpeedTest using Ookla Speedtest
# Description: SpeedTest using Ookla Speedtest for personal use
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# Empty the logs
> /var/log/dlspeedtest

## Modify this commands if you need to know upload speed or change target server id ##
## Define the needed CLI commands ##
SpeedTest=$(speedtest --server-id=12108)
DownLoad=$(echo "$SpeedTest" | grep Download: | cut -d\: -f2 | cut -d\. -f1 | xargs)

## Modify "275" to mbps of your ISP package ##
## Test if the internet download speed ##
if [ "$DownLoad" -lt "275" ]
then
  exit 0
else
  exit 124
fi
