#!/bin/bash

### BEGIN INIT INFO
# Provides: ISP Internet Speed Test
# Required-Start:  $local_fs $network
# Required-Stop:  $local_fs
# Default-Start:  2 3 4 5
# Default-Stop:  0 1 6
# Short-Description: ISP Internet Speed Test using Ookla Speedtest
# Description: ISP Internet Speed Test using Ookla Speedtest for personal use
### END INIT INFO

## Define the needed CLI commands ##
## Remove --server-id=12108 to target any server or change ID ##
SpeedTest=$(speedtest --server-id=12108)
DownLoad=$(echo "$SpeedTest" | grep Download: | cut -d\: -f2 | cut -d\. -f1 | xargs)
UpLoad=$(echo "$SpeedTest" | grep Upload: | cut -d\: -f2 | cut -d\. -f1 | xargs)
Url=$(echo "$SpeedTest" | grep URL:)
Date=`/bin/date`
## Your acceptable download / upload mbps speed parameter ##
ISPDLSpeed="275"
ISPULSpeed="200"

## Test if the internet download speed ##
if [[ "$DownLoad" -gt "$ISPDLSpeed" && "$UpLoad" -gt "$ISPULSpeed" ]]
# Change if just one way speed is concerned e.g. : if [ "$DownLoad" -gt "$ISPDLSpeed" ]
then
  echo -e "\nThe internet speed is $DownLoad Mbps for download and $UpLoad Mbps for upload.\nBoth are within acceptable parameter. No need to report to ISP.\n$Url\n"
else
  echo -e "\nThe internet speed is $DownLoad Mbps for download and $UpLoad Mbps for upload.\nThey are not acceptable. Do file report to ISP.\n$Url\n"
fi
